### ISSUE TITLE
Assign doesn't function or provide an error message

### ISSUE THREAD

**Issue by moxious** [ndaversa/hubot-jira-bot#11]
When talking to the bot via the gitter2 adapter, and assigning tickets like this:

`@botname assign OB-82 @username`

The bot responds by mentioning themselves, and then takes no action. No error or warning is printed in the logs.

E.g. the bot's response in this case would be:

`botname: @botname`

**Comment by ndaversa** [comment]
I haven't used that adapter but I'll try and take a look and see if I can figure out the issue. Can you point me to the adapter/service so I can try and bootstrap myself.

**Comment by moxious** [comment]
Using this adapter: https://github.com/huafu/hubot-gitter2

**Comment by ndaversa** [comment]
@moxious So I did some digging....

- The syntax you are trying to use is incorrect you should be using
`OB-82 assign @username`

- The gitter user fields are pretty limited: eg.
```
      "id": "REDACTED",
      "name": "Nino D'Aversa (ndaversa)",
      "login": "ndaversa",
      "avatarUrl": "https://avatars0.githubusercontent.com/u/427037?v=3&s=128",
      "url": "https://github.com/ndaversa",
      "room": "REDACTED"
```
which means it will be hard to lookup the corresponding JIRA user.

We use @slackhq as our adapter and that exposes an email address field that we can key off to match the JIRA user.

It would take some additional work to support gitter in tandem with that, a few things I think would be needed:
 - Config to specify how to resolve JIRA users (eg. which field from chat should be used to compare against the JIRA fields) 
- Updating a few utils here: https://github.com/ndaversa/hubot-jira-bot/blob/master/src/utils.coffee#L45-74
- also some reworking of stuff like this: https://github.com/ndaversa/hubot-jira-bot/blob/master/src/jira/assign.coffee#L9-12

Its non-trivial and not something I want to implement myself (as I'm not currently using this against a gitter deploy), but pull requests are welcomed. If you want to go that route it will be important to test against Slack as thats the main deployment target and if it fails/regresses the PR won't land.

For now I'm going to close the issue, let me know if you're interested in contributing back the fixes you would need for gitter support.

**Comment by moxious** [comment]
Understood - I might could go after a PR to do this, but as testing gitter is non-trivial for you, testing against slack is non-trivial for me.  I understand that the PR wouldn't land if there was a regression there, I'm not sure I'd take this on either.

Perhaps if this can't be solved so easily, at least the bot could provide a useful/descriptive error message.  Its present output is opaque and doesn't really mean anything.  Not all failure modes are easily dealt with, but I think it's reasonable for the bot to indicate clearly what the failure mode is.

**Comment by ndaversa** [comment]
@moxious in my testing this is the output:
<img width="254" alt="screen shot 2016-04-22 at 10 40 40 am" src="https://cloud.githubusercontent.com/assets/427037/14744893/b2905dd0-0876-11e6-88e3-fe5e1397d887.png">

I seems sufficient to me, do you agree?

**Comment by moxious** [comment]
It does seem sufficient, it's just that's not the output I get on gitter.

If I do something like WIA-134 assign @moxious the bot (@devetops) would respond with simply "@devetops" nothing further.

**Comment by ndaversa** [comment]
@moxious I'm not sure why that would be, I would suggest getting the latest version and seeing if thats still the case. I do publish releases very frequently
