### ISSUE TITLE
Is there a way to access Jira classes from outside of JiraBot?

### ISSUE THREAD

**Issue by jfreedman** [ndaversa/hubot-jira-bot#23]
Hi,

More of a question than an issue.  In my hubot script I am listening for the JiraWebhookTicketInReview.  When the event fires, I'd like to use some of the classes you have under /jira to do some additional custom functionality.

I am pretty new to nodejs and hubot and haven't been able to find a way to make this work.  Are those submodules (assuming my term is right) available for me to use via require or some other way?

Module.exports = (robot) ->
  robot.on "JiraWebhookTicketInReview", (ticket, transition, room, includeAttachment = no) =>
    console.log 'here'
    bot = require('hubot-jira-bot')
    #can't find a way to get access to jira classes from here

**Comment by ndaversa** [comment]
@jfreedman you could do something like this:

```
Jira = require( "./node_modules/hubot-jira-bot/src/jira" );
```

note the path to your node_modules would be relative to the file you do the require from

Then you could do things like

`Jira.Create.with(params go here)`
