### ISSUE TITLE
OAuth support?

### ISSUE THREAD

**Issue by dleblanc10** [ndaversa/hubot-jira-bot#25]
This jira bot is excellent.  We are a little concerned though about having a plain-text password as part of the setup.  Was looking into Jira's OAuth setup.  Seems a bit more secure (can't use OAuth token for an interactive session).  Has this been considered as a new feature? I'm considering trying to get it working and send back a pull request.  Looking for any gotchas if you've already tried it.

**Comment by ndaversa** [comment]
@dleblanc10 I haven't tried it before, so nothing to share on that front. You likely would need to build some endpoints and ship a page or two from the express server to handle the initial setup. I avoided doing it since it made it more complicated to get started.
