### ISSUE TITLE
SyntaxError: Unexpected token w in JSON at position 1

### ISSUE THREAD

**Issue by GregSharpe1** [ndaversa/hubot-jira-bot#28]
This is how my current command looks:

HUBOT_SLACK_TOKEN=xoxb-163461access_tokenYdVltrhwrbUl                            HUBOT_JIRA_GITHUB_DISABLED=true HUBOT_JIRA_PRIORITIES_MAP={"name":"Blocker","id":"1"}   HUBOT_JIRA_PROJECTS_MAP={"web":"WEB","android":"AN","ios":"IOS","platform":"PLAT"}      HUBOT_JIRA_TRANSITIONS_MAP={"name":"triage","jira":"Triage"}                            HUBOT_JIRA_TYPES_MAP={"story":"Story / Feature","bug":"Bug","task":"Task"}              HUBOT_JIRA_URL=https://mycompany.atlassian.net:9090 HUBOT_JIRA_USERNAME=gregsharpe   HUBOT_JIRA_PASSWORD=MY_PASSWORD ./bin/hubot --adapter slack

Has anyone got any ideas?

**Comment by ndaversa** [comment]
@GregSharpe1 likely its the way the strings (most importantly the `"`) are being interpreted by your shell. I would put single quotes around all the envvars to make sure you are sending in what you expect.

If you want to see what is actually making its way in, I recommend putting a `console.log` into the config.coffee and print out the value to see why it's breaking, It's almost surely not what you think and effectively bad json
