### ISSUE TITLE
TypeError: Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by GregSharpe1** [ndaversa/hubot-jira-bot#29]
Keep receiving this on various commands, 

HUBOT_SLACK_TOKEN='xoexample slack tokenUl' HUBOT_JIRA_GITHUB_DISABLED='true' HUBOT_JIRA_PROJECTS_MAP='{"web":"WEB","ops":"OPS"}' HUBOT_JIRA_TRANSITIONS_MAP='[{"name":"new","jira":"New"},{"name":"ready","jira":"Ready"},{"name":"assessing","jira":"Assess"},{"name":"active","jira":"Active"},{"name":"testing","jira":"Testing"},{"name":"feedback","jira":"Feedback"},{"name":"done","jira":"Done"}]' HUBOT_JIRA_TYPES_MAP='{"story":"Story","bug":"Bug","task":"Task","epic":"Epic"}' HUBOT_JIRA_PRIORITIES_MAP='[{"name":"Blocker","id":"1"},{"name":"Critical","id":"2"},{"name":"Major","id":"3"},{"name":"Minor","id":"4"},{"name":"Trival","id":"5"}]' HUBOT_JIRA_URL='https://company.atlassian.net' HUBOT_JIRA_FIELDS='["project"]' HUBOT_JIRA_USERNAME='gregsharpe' HUBOT_JIRA_PASSWORD='password' ./bin/hubot --adapter slack

Installed all required npm modules. Can't think of what it could be. Any help?

**Comment by Nijisha** [comment]
Hi,
I just wanted to create one project in jira and need to update the time sheet accordingly. Could you please tell me how to do this using this Hubot-jira plugin?
the following steps I did.. but I am stuck with some error.
1. I  installed all the npm modules and downloaded the project and updated the config.cofee . in ubuntu OS
2. Ran the command 'sudo hubot project:Test' in terminal
3. I am getting some error like '/usr/bin/env: coffee: No such file or directory'
 I am not sure the steps I followed is correct or not. I could find any step by step instructions to integrate it and create the projects through the hubot. 
could you please advice me on this. I am new to hubot. 

Thanks in advance

**Comment by ndaversa** [comment]
I might be that the env vars are not properly set?
