### ISSUE TITLE
Installation and configuration

### ISSUE THREAD

**Issue by craigwillis85** [ndaversa/hubot-jira-bot#3]
Hi

I'm trying to get this installed and configured on heroku.

I have followed the steps and I have the following in my heroku variables:

    HUBOT_JIRA_URL: https://MYURL.atlassian.net:9090
    HUBOT_JIRA_USERNAME: MY_USER 
    HUBOT_JIRA_PASSWORD: MY_PASSWORD
    HUBOT_JIRA_PROJECTS_MAP: {"test123":"TEST123"}
    HUBOT_JIRA_TYPES_MAP: {"epic":"Epic"}

I have installed the script via npm: `npm install hubot-jira-bot --save` and added it to the `external-scripts.json` and pushed to heroku

When I type `hubot help` I don't see any commands relating to JIRA

Have I installed this correctly?

**Comment by andrew-best-diaxion** [comment]
Confirmed. Have the same problem myself.
