### ISSUE TITLE
Search By JIRA NUMBER

### ISSUE THREAD

**Issue by mchennamsetty** [ndaversa/hubot-jira-bot#33]
Looks like we cant search by JIRA Number since jql is search for 'text' so adding 'key' in the fields is not working to perform search by JIRA Number. Ex: bot-name jira search ABC-4

https://jira.xxx.com/jira/rest/api/2/search
body is {"jql":"text ~ 'ABC-4'","startAt":0,"maxResults":5,"fields":["issuetype","status","assignee","reporter","summary","description","labels","project"]}

Any Suggestions please!!

**Comment by vwbusguy** [comment]
If you just give the number without any arguments, it will give the issue detail.  Just referencing ABC-4 in-chan will give the details about the ABC-4 ticket.

**Comment by mchennamsetty** [comment]
Thank you. Appreciated
