### ISSUE TITLE
enabling buttons in slack question

### ISSUE THREAD

**Issue by yohayg** [ndaversa/hubot-jira-bot#38]
Hi @ndaversa and all,

Thanks a lot for the plugin.
It works fine.

I have a question regarding enabling the buttons.
The buttons appear after I create a bug. But when one is clicked I get an error in the channel:
"Darn – that didn’t work. Only Slack Apps can add interactive elements to messages"

Is there a guide how to enable these buttons?

Thanks,

Yohay

**Comment by ndaversa** [comment]
@yohayg Thanks. You will need to make a Slack App: https://api.slack.com/apps?new_app=1

this will allow you to use the buttons, you will need to setup a server to handle the callbacks, but its all documented on slacks end
